import time, os

    # print(" ____________________________________________________________________________________________________")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print("|                                                                                                    |")
    # print(" ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")

def windResize():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(" R̲e̲s̲i̲z̲e̲________________________________________________________________________________________________")
    print("|                                                                                                      |")
    print("|                               Please resize your window to fit this box                              |")
    print("|                                        Press Return to Continue                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("|                                                                                                      |")
    print("  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
    return

def mainScreen():
    print(" M̲a̲i̲n̲_P̲a̲ge̲___________________________________________________________________________________________")
    print("|   `       .         ,       *         '   .          `         `       .      `      '         ,   |")
    print("|     @         `         ,       -Star Wars Informational Navigator-      .        `             .  |")
    print("|          `           .          .      'c' for characters          .            ,         *        |")
    print("|   .          __                          'p' for planets       `          '            ,           |")
    print("|            / *  \           .             'f' for films       .            ,                       |")
    print("|       `    \    /                        'v' for vehicles             `          `           @     |")
    print("|              ‾‾       `         '       's' for starships       ,                      `           |")
    print("|   \"                      '           .                 .                    *               '      |")
    print("|                .                               \"                                                   |")
    print("|   `    ,                               '                                                |_/‾‾\_|   |")
    print("|                       @          `         'q' for quit          \"       `     '        |‾\__/‾|   |")
    print("|    `         *               ,      '           ,             `       ,                            |")
    print(" ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
    return

def charScreen():
    print(" ____________________________________________________________________________________________________")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print("|                                                                                                    |")
    print(" ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")